### ISSUE TITLE
Mark download as compatible with 1.19.1 and 1.19.2

### ISSUE THREAD

**Issue by magneticflux-** [seaneoo/wpit#4]
Right now, `ferium` resolves the 1.18.2 version when searching for 1.19.2 because there are no exact matches and the 1.18.2 version was uploaded most recently.

**Comment by seaneoo** [comment]
Marked [1.5.1](https://modrinth.com/mod/wpit/version/1.5.1) as compatible with 1.19 - 1.19.2.

**Comment by magneticflux-** [comment]
Oof, I forgot I changed the mod json manually. You need to relax the version requirement to `>=1.19` or `1.19.x`: https://github.com/seaneoo/wpit/blob/fe7f786a35f82e41df7182caecc6a7c7945ef8bd/src/main/resources/fabric.mod.json#L34

```
[18:35:01] [main/ERROR]: Incompatible mod set!
org.quiltmc.loader.impl.FormattedException: org.quiltmc.loader.impl.discovery.ModSolvingException: Unhandled error involving mod 'WPIT' (wpit) v1.5.1+1.19:
Dependency for mod 'wpit' on minecraft versions [=1.19] (0 valid options, 1 invalid options)
	x mod 'minecraft' version 1.19.2 loaded from .quilt\remappedJars\minecraft-1.19.2-0.17.6\client-intermediary.jar
	at org.quiltmc.loader.impl.QuiltLoaderImpl.load(QuiltLoaderImpl.java:214) ~[quilt-loader-0.17.6.jar:?]
	at org.quiltmc.loader.impl.launch.knot.Knot.init(Knot.java:141) ~[quilt-loader-0.17.6.jar:?]
	at org.quiltmc.loader.impl.launch.knot.Knot.launch(Knot.java:70) [quilt-loader-0.17.6.jar:?]
	at org.quiltmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:24) [quilt-loader-0.17.6.jar:?]
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:578) ~[?:?]
	at org.prismlauncher.impl.OneSixLauncher.invokeMain(OneSixLauncher.java:104) [NewLaunch.jar:?]
	at org.prismlauncher.impl.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:176) [NewLaunch.jar:?]
	at org.prismlauncher.impl.OneSixLauncher.launch(OneSixLauncher.java:186) [NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:144) [NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:74) [NewLaunch.jar:?]
Caused by: org.quiltmc.loader.impl.discovery.ModSolvingException: Unhandled error involving mod 'WPIT' (wpit) v1.5.1+1.19:
Dependency for mod 'wpit' on minecraft versions [=1.19] (0 valid options, 1 invalid options)
	x mod 'minecraft' version 1.19.2 loaded from .quilt\remappedJars\minecraft-1.19.2-0.17.6\client-intermediary.jar
	at org.quiltmc.loader.impl.solver.ModSolver.fallbackErrorDescription(ModSolver.java:615) ~[quilt-loader-0.17.6.jar:?]
	at org.quiltmc.loader.impl.solver.ModSolver.findCompatibleSet(ModSolver.java:244) ~[quilt-loader-0.17.6.jar:?]
	at org.quiltmc.loader.impl.discovery.ModResolver.resolve(ModResolver.java:434) ~[quilt-loader-0.17.6.jar:?]
	at org.quiltmc.loader.impl.QuiltLoaderImpl.setup(QuiltLoaderImpl.java:223) ~[quilt-loader-0.17.6.jar:?]
	at org.quiltmc.loader.impl.QuiltLoaderImpl.load(QuiltLoaderImpl.java:212) ~[quilt-loader-0.17.6.jar:?]
	... 10 more
```

**Comment by Sqaaakoi** [comment]
Please make sure to use >= in future!

**Comment by triphora** [comment]
1.5.1 has been unmarked as 1.19.1/.2 compatible on Modrinth. @seaneoo Please upload a new version with a fixed fabric.mod.json file.

**Comment by seaneoo** [comment]
My apologies everyone, this has now been properly fixed. I uploaded [release 1.5.1-1.19.x](https://github.com/seaneoo/wpit/releases/tag/v1.5.1%2B1.19.x) to support 1.19 - 1.19.2.
